# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 1f00f4fde1063b51fb9beae92b3f32db9aa04450c0bdb801aedc65659a4aac4d3c589a83c7ca3d27de80a8719c8e1d41fc351e536593c8c045c59a030019f974

test:
  secret_key_base: c73a36e19ac43873ab7e68460e7d2df6e0a91f923b9c292bd22b2603473235b772bc91784de88466fa1fb9e1eaa361b1cf12b5944d1f3711f52638d0d01394fb

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
