# Put your wisdoms here

---
- Call your parents
- Perform kegel exercises; nobody will know until it counts
- Not washing your mouth out after brushing your teeth will let the fluoride continue to do its job
- Go outside
- Take a walk and look at things
